### ISSUE TITLE
Consider using Elemental API instead of native JavaScript

### ISSUE THREAD

**Issue by tehapo** [vaadin/responsive#1]
Consider using Elemental API instead of native JavaScript. At least some things to consider:
- code maintainability
- widgetset size

I have already forked the project and rewrote the `ResponsiveConnector` using Elemental. My fork is a fairly direct rewrite and should be cleaned up further. Also currently seems that it's broken on Internet Explorer 8, but works on IE9 (will look into it soon).

https://github.com/tehapo/responsive

**Comment by jouni** [comment]
Wontfix for now (sorry @tehapo).

**Comment by tehapo** [comment]
@jouni No worries. 😆
