### ISSUE TITLE
Range format is too strict

### ISSUE THREAD

**Issue by magi42** [vaadin/responsive#10]
You can give open-ended high range such as "`600px-`", but low open-ended range "`-200px`" does not work, it currently has to be "`0-200px`".

While you don't need to give "`px`" in the "`0-200px`", you do need to give it otherwise - "`100-200px`" is invalid, it is currently required to be "`100px-200px`".

Is "px" the only possible measure? If so, maybe could just leave it out.

**Comment by jouni** [comment]
Wontfix for now.
