### ISSUE TITLE
Security exception with superdevmode and firefox

### ISSUE THREAD

**Issue by mhosio** [vaadin/responsive#11]
When the add-on is used in superdevmode with firefox, the css parsing fails with Uncaught client side exception if there are style sheets from other add-ons. 

Steps to reproduce: 
Create a new vaadin 7 project.
Add responsive add-on and any other add-on that has embedded styles (for example drag and drop layouts).
Extend the example project UI with responsive
Run in firefox using superdevmode
-> Uncaught client side exception

Possible cause: There are style sheets from multiple urls / port (the actual test server and the code server ) -> security exception in firefox

**Comment by jouni** [comment]
Wontfix for now. If you really need this to be fixed, please repost this issue in https://github.com/vaadin/framework/
