### ISSUE TITLE
width-range style applied only after reload

### ISSUE THREAD

**Issue by gabosvk** [vaadin/responsive#7]
Hi,

I'm facing an issue with setting responsive layout. I have a CssLayout (mainLayout) with 1170px width  and I'm trying to resize it when the screen size goes under 1170 px (setting it to 95% of screen size). This layout is aligned TOP_CENTER of 100% x -1px VerticalLayout (rootLayout). Every time I set my browser more than 1170px wide and reload the page mainLayout is wide and centered as expected. However, when I start to resize the width of browser, mainLayout loses "responsive behavior" and keeps it's original size 1170px.  When I set the browser width to let's say 800px and reload the page, the width of mainLayout goes to 95% as expected but after making screen wider (more than 1170px) it stays on 95% and doesn't go to 1170px. What I wanted to say is that the "responsive behavior" is visible (applied) only after page reloading, not during setting the browser width dynamically. 

Herewith the css:
.rootLayout {
    background: #ccccc;
}
.mainLayout[width-range~="0-1169px"] {
        width: 95%;
    }

```
.mainLayout[width-range~="1170px-"] {
    width: 1170px;
}
```

Java:
VerticalLayout rootLayout = new VerticalLayout();
rootLayout.addStyleName("rootLayout");
rootLayout.setWidth("100%");
rootLayout.setHeight("-1px");
rootLayout.setMargin(false);

CssLayout mainLayout = new CssLayout();
mainLayout.addStyleName("mainLayout");
rootLayout.addComponent(mainLayout);
rootLayout.setComponentAlignment(mainLayout, Alignment.TOP_CENTER);

new Responsive(this);
new Responsive(rootLayout);
new Responsive(mainLayout);

**Comment by guglielmomoretti** [comment]
Hi, 

I'm, developing a new webapp with vaadin. I bumped into the same issue. Setting the height (in my case) to  100% in the java code, successfully solved the issue.

Just to know, is this issue something will be addressed in the near future or not? 

Regards

**Comment by jouni** [comment]
Hi, @guglielmomoretti!

The Responsive extension is nowadays a part of the core Vaadin Framework, and this issue is actually tracked in https://github.com/vaadin/framework/issues/5810

I’ll edit the readme for this project to point people to report issues in the framework instead of here.
